# Generated by Django 2.2 on 2020-03-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'managed': True, 'verbose_name': 'Обо мне', 'verbose_name_plural': 'Обо мне'},
        ),
    ]
