# Generated by Django 2.2.10 on 2020-03-19 10:11

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='description',
            field=martor.models.MartorField(blank=True, max_length=5000, null=True, verbose_name='Описание'),
        ),
    ]
