# Generated by Django 2.2 on 2020-03-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_documentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('documentation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Documentation')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
            bases=('content.documentation',),
        ),
        migrations.CreateModel(
            name='Conferences',
            fields=[
                ('documentation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Documentation')),
            ],
            options={
                'verbose_name': 'Конференция',
                'verbose_name_plural': 'Конференции',
            },
            bases=('content.documentation',),
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('documentation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Documentation')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
            bases=('content.documentation',),
        ),
        migrations.CreateModel(
            name='Presentations',
            fields=[
                ('documentation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Documentation')),
            ],
            options={
                'verbose_name': 'Презентация',
                'verbose_name_plural': 'Презентации',
            },
            bases=('content.documentation',),
        ),
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('documentation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Documentation')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
            },
            bases=('content.documentation',),
        ),
        migrations.CreateModel(
            name='Webinars',
            fields=[
                ('documentation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Documentation')),
            ],
            options={
                'verbose_name': 'Вебинар',
                'verbose_name_plural': 'Вебинары',
            },
            bases=('content.documentation',),
        ),
        migrations.AlterModelOptions(
            name='documentation',
            options={'verbose_name': 'Документация', 'verbose_name_plural': 'Документация'},
        ),
    ]
