# Generated by Django 2.2 on 2020-03-11 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20200311_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('documentation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Documentation')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
            bases=('content.documentation',),
        ),
    ]
